name: telecom_analytics
version: '1.0.0'
config-version: 2
profile: telecom_analytics
model-paths: ["models"]
models:
  telecom_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: table
